# Generated by Django 2.1.7 on 2020-04-25 08:05

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='文章标题')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='发布日期')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否展示')),
                ('content', DjangoUeditor.models.UEditorField(verbose_name='文章内容')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='upimages/thumbnail/', verbose_name='缩略图')),
            ],
            options={
                'verbose_name': '新闻资讯',
                'verbose_name_plural': '新闻资讯',
            },
        ),
        migrations.CreateModel(
            name='NewsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='分类名称')),
            ],
            options={
                'verbose_name': '资讯类别',
                'verbose_name_plural': '资讯类别',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='news_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.NewsType', verbose_name='文章分类'),
        ),
    ]
