# Generated by Django 2.1.7 on 2020-04-25 09:51

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='upimages/thumbnail/', verbose_name='缩略图'),
        ),
    ]
