# Generated by Django 2.1.7 on 2020-04-25 09:55

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200425_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(default='upimages/thumbnail/default.jpg', upload_to='upimages/thumbnail/', verbose_name='缩略图'),
        ),
    ]
