# Generated by Django 2.1.7 on 2020-04-26 06:10

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200425_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='产品名称')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='发布日期')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否展示')),
                ('content', DjangoUeditor.models.UEditorField(verbose_name='产品介绍')),
                ('thumbnail', imagekit.models.fields.ProcessedImageField(default='upimages/thumbnail/default.jpg', upload_to='upimages/thumbnail/', verbose_name='缩略图')),
            ],
            options={
                'verbose_name': '产品介绍',
                'verbose_name_plural': '产品介绍',
            },
        ),
        migrations.CreateModel(
            name='ProductsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='产品种类')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='upimages/products/', verbose_name='图片')),
            ],
            options={
                'verbose_name': '产品种类',
                'verbose_name_plural': '产品种类',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ProductsType', verbose_name='产品种类'),
        ),
    ]
