# Generated by Django 2.1.7 on 2020-04-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200426_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='productstype',
            name='thumbnail',
            field=models.ImageField(blank=True, default='upimages/thumbnail/default.jpg', null=True, upload_to='upimages/products/', verbose_name='图片'),
        ),
    ]
