# Generated by Django 2.1.7 on 2020-04-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200427_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstype',
            name='thumbnail',
            field=models.ImageField(blank=True, default='upimages/thumbnail/default.jpg', null=True, upload_to='upimages/products/', verbose_name='图片'),
        ),
    ]
