# Generated by Django 2.1.7 on 2020-04-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_newstype_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='add_time',
            field=models.DateField(auto_now=True, verbose_name='发布日期'),
        ),
    ]
