# Generated by Django 2.1.7 on 2020-04-28 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20200428_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='text',
            field=models.TextField(null=True, verbose_name='简介'),
        ),
        migrations.AddField(
            model_name='newstype',
            name='text',
            field=models.TextField(null=True, verbose_name='简介'),
        ),
        migrations.AddField(
            model_name='product',
            name='text',
            field=models.TextField(null=True, verbose_name='简介'),
        ),
        migrations.AddField(
            model_name='productstype',
            name='text',
            field=models.TextField(null=True, verbose_name='简介'),
        ),
    ]
