# Generated by Django 2.1.7 on 2020-04-28 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20200428_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('tel', models.CharField(max_length=20, verbose_name='手机号')),
                ('sex', models.CharField(max_length=10, verbose_name='性别')),
                ('question', models.TextField(null=True, verbose_name='咨询的内容')),
                ('is_quest', models.BooleanField(default=False, verbose_name='是否已联系')),
            ],
            options={
                'verbose_name': '客户咨询',
                'verbose_name_plural': '客户咨询',
            },
        ),
    ]
